### ISSUE TITLE
Maven plugin download

### ISSUE THREAD

**Issue by martin-g** [michelou/dotty-examples#2]
https://github.com/michelou/dotty-examples/tree/master/examples#maven-build-tool says that the new Maven plugin can be download as a Zip archive but I cannot find the link to it.

**Comment by michelou** [comment]
@martin-g The Maven plugin is located in the [`bin/`](https://github.com/michelou/dotty-examples/tree/master/bin) directory; I did not try it for a long time (`Dotty 0.27` I think), so it may not work anymore with `Scala 3.0.0-Mx` (another piece of code I should update).

**Comment by martin-g** [comment]
Thank you, @michelou !
